### ISSUE TITLE
Drawer visual bug 

### ISSUE THREAD

**Issue by SbrowneA** [oatmael/Sneezy#10]
On back pressed, the navigate menu shows the previous fragment as selected.

steps to replicate:
1. Navigate to fragment other than the home fragment
2. Go back using the phones navigate button
3. Open hamburger menu

![Screenshot_20200818-102731_SneezyApplication](https://user-images.githubusercontent.com/61568703/90458760-6d86e380-e13e-11ea-877b-37c33c3122da.jpg)

![Screenshot_20200818-102739_SneezyApplication](https://user-images.githubusercontent.com/61568703/90458765-6f50a700-e13e-11ea-9702-0f7b938b927a.jpg)

![Screenshot_20200818-102745_SneezyApplication](https://user-images.githubusercontent.com/61568703/90458767-6f50a700-e13e-11ea-8a08-906c3bb1f085.jpg)

**Comment by lost0000** [comment]
Fixed and pushed
