### ISSUE TITLE
"Rate Sneezy" popup appears on first open 

### ISSUE THREAD

**Issue by SbrowneA** [oatmael/Sneezy#11]
The "Rate Sneezy" popup appears on the first open from a fresh install

**Comment by lost0000** [comment]
If its a fresh install its meant to open. You mean you've wiped it yea?

**Comment by lost0000** [comment]
Cant really detect whether the apps been uninstalled then reinstalled i dont think

**Comment by lost0000** [comment]
Oh actually I get you now, thats bad ill get on that

**Comment by lost0000** [comment]
Fixed
