### ISSUE TITLE
Notification bar text not visible in light mode

### ISSUE THREAD

**Issue by SbrowneA** [oatmael/Sneezy#14]
The text on the notification bar is the same colour as the white background in light mode.

some pics for comparison:
![image](https://user-images.githubusercontent.com/61568703/90958311-c6ee6a00-e4d2-11ea-8831-7d6b3a480e24.png)
![image](https://user-images.githubusercontent.com/61568703/90958317-d2da2c00-e4d2-11ea-9ede-0762138abb83.png)

**Comment by lost0000** [comment]
Fixed up, changed to black
