### ISSUE TITLE
Graphs not showing weekly values only

### ISSUE THREAD

**Issue by SbrowneA** [oatmael/Sneezy#16]
The graph seems to be showing the lifetime sneeze count for each day rather than the weekly count.
I can only confirm this is occurring on on the experimental branch since I have not been able to log in on master.

(Saturday 22 Aug/ Thursday 27 Aug)
![Screenshot_20200827-181046_Sneezy](https://user-images.githubusercontent.com/61568703/91650923-1f21ff00-eac5-11ea-9f7a-a0e8dfb7b394.jpg)

(Saturday 29 Aug)
![Screenshot_20200829-184144_Sneezy](https://user-images.githubusercontent.com/61568703/91650921-1c270e80-eac5-11ea-88e1-ba62d23a8b00.jpg)

![Screenshot_20200829-184209_Sneezy](https://user-images.githubusercontent.com/61568703/91650922-1e896880-eac5-11ea-9bad-c9a7e84b1d45.jpg)

**Comment by IsaacHogben** [comment]
Found what was causing this and it should work now if you could give it another look @SbrowneA. However this bug does suggest that the **getWeeklyUserSneezeItems** is retrieving more than just one weeks worth of data. This issue may come up later @oatmael.

**Comment by SbrowneA** [comment]
seems to be fixed

![Screenshot_20200831-154519_Sneezy](https://user-images.githubusercontent.com/61568703/91688762-eb68d700-eba1-11ea-8751-e33b49c72be2.jpg)
