### ISSUE TITLE
Error inflating class @ line 35 activity_main.xml

### ISSUE THREAD

**Issue by oatmael** [oatmael/Sneezy#4]
Lower API levels (min 22) do not support the following content, and will throw an exception at launch when attempting to inflate:
![image](https://user-images.githubusercontent.com/45870261/89369392-23086e80-d71d-11ea-86fd-315730f2d1cd.png)
![image](https://user-images.githubusercontent.com/45870261/89369538-8befe680-d71d-11ea-807b-1fe5891ff67e.png)

Potential Fixes:
Rework view to support lower API levels
Push minimum API level up

**Comment by lost0000** [comment]
SDK Changed to 24 in latest PUSH, should be A OK now
