### ISSUE TITLE
HomeFragment Sneeze report not updating on launch

### ISSUE THREAD

**Issue by lost0000** [oatmael/Sneezy#6]
So the "Youve sneezed x amount of times" wont update untill a sneeze has occured.
On launch:
https://gyazo.com/f8e224f491140018d315812c5befab55

After Sneeze:
https://gyazo.com/d9c45da3175d9112b5194cb797a836a7

Not sure if its because of my code(missing a db info pull in my if else statements?) or something db related that needs to happen on app launch.

**Comment by oatmael** [comment]
Related to this issue, increasing or decreasing sneeze amount will correctly update the sneeze amount.
